### ISSUE TITLE
预训练的模型没法直接用来测试

### ISSUE THREAD

**Issue by qiuyajun** [xinntao/ESRGAN#10]
您好,首先感谢下您的代码,对我有很大的帮助,但现在有一个问题,想请教您一下,使用您提供的训练好的模型进行跑您的测试代码时,会出现如下问题
root@c07bd16360cb:/home/qiuyj/ESRGAN# python test.py models/RRDB_ESRGAN_x4.pth
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RRDB_Net:
	Missing key(s) in state_dict: "model.9.bias", "model.9.weight". 
	Unexpected key(s) in state_dict: "model.1.sub.2.RDB1.conv1.0.weight", "model.1.sub.2.RDB1.conv1.0.bias", "model.1.sub.2.RDB1.conv2.0.weight", "model.1.sub.2.RDB1.conv2.0.bias", "model.1.sub.2.RDB1.conv3.0.weight", "model.1.sub.2.RDB1.conv3.0.bias", "model.1.sub.2.RDB1.conv4.0.weight", "model.1.sub.2.RDB1.conv4.0.bias", "model.1.sub.2.RDB1.conv5.0.weight", "model.1.sub.2.RDB1.conv5.0.bias", "model.1.sub.2.RDB2.conv1.0.weight", "model.1.sub.2.RDB2.conv1.0.bias", "model.1.sub.2.RDB2.conv2.0.weight", "model.1.sub.2.RDB2.conv2.0.bias", "

**Comment by qiuyajun** [comment]
@xinntao

**Comment by qiuyajun** [comment]
还有一个问题想请教您一下,就是假设训练用的HR图片的大小是124x124的,但数据集的图片都是1024x2048,这个时候应该怎么用1024x2048的图片的产生124x124,是用随机裁剪的方式吗,还是其他什么方式,您认为哪一种方式好一点. @xinntao

**Comment by xinntao** [comment]
Hi @qiuyajun 
I have not encountered your problems. I saw that you use python2.7, and I am not sure whether it causes the problem. I've tested in Python 3 and PyTorch >= 0.4.0.

You can print more information to debug.
For example, printing the model parameters dict after constructing the model.
```

state_dict = model.state_dict()
for key, param in state_dict.items():
    print(key)
```

**Comment by xinntao** [comment]
@qiuyajun 
For the data, I think random cropping is good. For faster IO, you can first crop to sub-images and use  lmdb format. Some discussions can be found [here](https://github.com/xinntao/BasicSR/wiki/Faster-IO-speed).

**Comment by qiuyajun** [comment]
好的,谢谢您啦@xinntao
