### ISSUE TITLE
Can you show an example of an SR image after training stage 1?

### ISSUE THREAD

**Issue by qAp** [xinntao/ESRGAN#109]
In your paper you say that "The  training  process  is  divided  into  two  stages.  First,  we  train  a  PSNR-oriented model with the L1 loss.  The learning rate is initialized as 2×10^−4 and decayed by a factor of 2 every 2×10^5 of mini-batch updates."  

Can you please show an example of an image output by the generator, along with the real image, after this first stage is completed?  It'd really help me know if I'm on the right track.

The number of mini-batches to train for in this stage 1.  Is it just enough to get the PSNR to level off?

Slightly unrelated.  The generation of low resolution images uses the 'bicubic' method.  Does ESRGAN only work for this method, or the algorithm doesn't really depend on the way with which the LR images are generated?

Thanks

**Comment by xinntao** [comment]
We have released the first stage model: https://drive.google.com/drive/folders/15DgDtfaLASQ3iAPJEVHQF49g9msexECG for ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth

now ESRGAN relies heavily on the trained bicubic kernel.
