### ISSUE TITLE
Problems with direct training：TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by xiaoyi-st** [xinntao/ESRGAN#113]
**model_path = 'models/RRDB_ESRGAN_x4.pth'  # models/RRDB_ESRGAN_x4.pth OR models/RRDB_PSNR_x4.pth**
**device = torch.device('cpu')  # if you want to run on CPU, change 'cuda' -> cpu**
# device = torch.device('cpu')

**test_img_folder = './LR'**

**model = arch.RRDBNet(3, 3, 64, 23, gc=32)**
Directly use the original data set for training, the model is also downloaded, the above problem occurs, I am confused, and hope to get your help

**Comment by xinntao** [comment]
@xiaoyi-st 
some of the variables are None type. 
You may not load the image, check the image loading
