### ISSUE TITLE
为什么我使用自己修改的rrdb之后训练进行插值会得到这个bug

### ISSUE THREAD

**Issue by beiyu555** [xinntao/ESRGAN#124]
(pytorch) D:\Python file\ESRGAN-master>python net_interp.py 0.5
Interpolating with alpha =  0.5
Traceback (most recent call last):
  File "net_interp.py", line 19, in <module>
    net_interp[k] = (1 - alpha) * float(v_PSNR) + alpha * float(v_ESRGAN)
TypeError: float() argument must be a string or a number, not 'collections.OrderedDict'

**Comment by Shelsin** [comment]
所以楼主这个问题怎么解决啊，是要把python版本降低吗
