### ISSUE TITLE
issues about  smaller initialization and instance norm

### ISSUE THREAD

**Issue by liang233** [xinntao/ESRGAN#29]
hello, smaller initialization can help to train a very deep network in your paper, if I use instance norm，can I need smaller initialization? thanks

**Comment by xinntao** [comment]
From our experiments, smaller initialization helps the convergence for very deep networks without normalization layers. 

With instance norm, the convergence seems to be not a problem.
I think whether you use smaller initialization or not will not bring lots of differences.

**Comment by liang233** [comment]
thanks
