### ISSUE TITLE
What is the minimum requirements to run ESRGAN in general?

### ISSUE THREAD

**Issue by tommai78101** [xinntao/ESRGAN#30]
I was testing ESRGAN out on a workstation when I realized CUDA 2.1 is not supported for PyTorch. 

I'm assuming that also means ESRGAN is not supported because of CUDA 2.1.

But to be exact, I don't see any minimum requirements to run ESRGAN. Thus, I have to come to this conclusion the hard way.

To prevent such things from happening, I would like to request on the README.md to list out the minimum requirements to properly run ESRGAN.

* What Nvidia CUDA version is required?
* What Nvidia architecture is needed? (Fermi, Volta, Pascal, Turing, etc.?)
* What Nvidia card type and up can be used? (Quadro, NVS, GeForce?)

Thanks.

**Comment by xinntao** [comment]
@tommai78101 
Currently, you can use pytorch > 0.4.1 for ESRGAN. 
The required CUDA version depends on which pytorch you installed (can be found https://pytorch.org/get-started/previous-versions/ ).

I think Nvidia arch and Nvidia card type are not important because they will be handled by CUDA.

**Comment by tommai78101** [comment]
Since you mentioned you require Pytorch >= 0.4.0, Pytorch 0.4.0 supports at minimum CUDA 8.

CUDA 2.1 was released 12 years ago, just saying.

**Comment by xinntao** [comment]
@tommai78101 
It seems that pytorch does not support cuda2.1. 
You need to update the cuda version.

**Comment by tommai78101** [comment]
@xinntao 

Yep, hence my request for you to add just an extra bit of info to your README.md, stating that PyTorch requires minimum of CUDA 8.0. This is the missing info that's left out in the Dependencies section.

**Comment by xinntao** [comment]
Thanks, I will add it.

**Comment by tommai78101** [comment]
Closing this issue because the commit addressed this issue.

**Comment by heetshah16** [comment]
How can I run testing for CPU 
it is showing no nvidia driver found error

**Comment by ghost** [comment]
@tommai78101  @xinntao 
Do not confuse CUDA Compute Capability with CUDA **(SDK)** version.
The CUDA (compute capability) 2.1 is for Fermi, and CUDA (SDK) version for Fermi is 3.0 - 8.0.


The issue should be reopened.

- What Nvidia CUDA **Compute Capability** is required? For ESRGAN/**Real-ESRGAN**.
- What Nvidia **architecture** is needed? (Fermi, Volta, Pascal, Turing, etc.?)
