### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by cyberfunk** [xinntao/ESRGAN#44]
After running the ESRGAN test on a 12" 240dpi 6000 pixel file the process fails with:

Killed: 9

Does anyone know what this means and how I can get the process to complete successfully?

**Comment by rowanG077** [comment]
I have the same issue.

**Comment by xinntao** [comment]
Could you provide more info, like the error log?

**Comment by kenrubiooo** [comment]
Your image file may be too big to be processed.

**Comment by cyberfunk** [comment]
Thanks I think I'll have to save some money and pay for Topaz Labs A.I. Gigapixel. I was hoping for a free solution that could match Topaz quality but have not found one yet.
