### ISSUE TITLE
about the results you provided

### ISSUE THREAD

**Issue by cyforsr** [xinntao/ESRGAN#46]
When I compute the psnr between the HR images and the SR images you provided in  Google Drive. The psnr of your SR baboon image in Google drive is 18.57dB, but in your paper the value is 20.35dB. Can you provide the psnr.py? or tell me what happened about my code?   and I use skimage.measure.compare_psnr( )
![image](https://user-images.githubusercontent.com/37731329/55631385-78133800-57ea-11e9-89f3-73b4799f6a8e.png)

**Comment by xinntao** [comment]
We have tested on the  Y channel. I think you may evaluate on RGB channels.  It is described in Sec4.3 in the ESRGAN paper.

**Comment by cyforsr** [comment]
The psnr value is 20.35dB. You are right.
