### ISSUE TITLE
生成lmdb文件时出现了除0的错误

### ISSUE THREAD

**Issue by adaxidedakaonang** [xinntao/ESRGAN#47]
问题出现在progress_bar.py文件中的update函数`fps = self.completed / elapsed`这里elapsed变成零了。我把`elapsed = time.time() - self.start_time`中的两个值打印出来发现是一样的：
Read images...
[                                                  ] 0/36352, elapsed: 0s, ETA:
Start...
1554711715.5890906
1554711715.5890906
0.0
Traceback (most recent call last):
  File "create_lmdb.py", line 22, in <module>
    pbar.update('Read {}'.format(v))
  File "D:\code\BasicSR\codes\utils\progress_bar.py", line 43, in update
    fps = self.completed / elapsed
ZeroDivisionError: float division by zero
其中我的路径设置是这样的：
img_folder = 'D:\\code\\BasicSR\\codes\\data\\HR\\*.png' 
lmdb_save_path = 'D:\\code\\BasicSR\\codes\\data\\HR.lmdb'
需要您的帮助！谢谢

**Comment by adaxidedakaonang** [comment]
抱歉这个问题应该在BasicSR中

**Comment by xinntao** [comment]
If the problem arises from the pbar, you can just comment these lines, which will not influence its function.

**Comment by adaxidedakaonang** [comment]
It works, thank you.感谢
