### ISSUE TITLE
keep going if some file processing fail ?

### ISSUE THREAD

**Issue by satsukiyatoshi** [xinntao/ESRGAN#51]
Hello.
When i use the test.py all is working great, but if i have some picture bigger than my computer can process in a whole set of picture, the processing stops then it can't process one file.
Is there any way to keep the processing going to the nexts file in case of processing error on one file ?

thanks

**Comment by xinntao** [comment]
1. If just want to skip these files, you can use `try ... except`
2. If you want to process these large files, you can first split the large image to several sub-images (for example, 4 parts) and then process them individually. Finally,  splice them to a large image.

**Comment by satsukiyatoshi** [comment]
Thank the try except did the trick
