### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by suke27** [xinntao/ESRGAN#6]
Hello, i try to run test.py with python 2.7 below errors occurred:

weiyang.su@deeplearning:~/Super_Resolution/ESRGAN-master$ python test.py models/RRDB_PSNR_x4.pth 
models/RRDB_PSNR_x4.pth
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/home/weiyang.su/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RRDB_Net:
        Missing key(s) in state_dict: "model.1.sub.1.bias", "model.1.sub.1.weight", "model.5.bias", "model.5.weight", "model.7.bias", "model.7.weight". 
        Unexpected key(s) in state_dict: "model.8.weight", "model.8.bias", "model.10.weight", "model.10.bias", "model.1.sub.2.RDB1.conv1.0.weight", "model.1.sub.2.RDB1.conv1.0.bias", "model.1.sub.2.RDB1.conv2.0.weight", "model.1.sub.2.RDB1.conv2.0.bias", "model.1.sub.2.RDB1.conv3.0.weight", "model.1.sub.2.RDB1.conv3.0.bias", "model.1.sub.2.RDB1.conv4.0.weight", "model.1.sub.2.RDB1.conv4.0.bias", "model.1.sub.2.RDB1.conv5.0.weight", "model.1.sub.2.RDB1.conv5.0.bias", "model.1.sub.2.RDB2.conv1.0.weight", "model.1.sub.2.RDB2.conv1.0.bias", "model.1.sub.2.RDB2.conv2.0.weight", "model.1.sub.2.RDB2.conv2.0.bias", "model.1.sub.2.RDB2.conv3.0.weight", "model.1.sub.2.RDB2.conv3.0.bias", "model.1.sub.2.RDB2.conv4.0.weight", "model.1.sub.2.RDB2.conv4.0.bias", "model.1.sub.2.RDB2.conv5.0.weight", "model.1.sub.2.RDB2.conv5.0.bias", "model.1.sub.2.RDB3.conv1.0.weight", "model.1.sub.2.RDB3.conv1.0.bias", "model.1.sub.2.RDB3.conv2.0.weight", "model.1.sub.2.RDB3.conv2.0.bias", "model.1.sub.2

do you face similar problem?

**Comment by xinntao** [comment]
@suke27 
I do not have the same problem. 

I checked the RRDB_PSNR_x4.pth and it does not have some keys the error mentioned, "model.7.bias", "model.7.weight". Did you change the network architecture? OR maybe is it the version problem? I test on python3.6 with pytorch 0.4.1
