### ISSUE TITLE
The training datasets of the trained PSNR-oriented model

### ISSUE THREAD

**Issue by Zheng222** [xinntao/ESRGAN#7]
@xinntao Hello, I want to know that the training datasets of the trained PSNR-oriented model. Is it three datasets DIV2K, Flickr2K, and OutdoorSceneTraining dataset?

**Comment by xinntao** [comment]
Hi, @Zheng222 
We use the DF2K (DIV2K & Flickr2K) to train the PSNR-oriented models.

In our experiments, the dataset for the pre-trained PSNR-oriented model is not so important. Using a pre-trained model with the only DIV2K dataset is able to achieve similar visual performance.

**Comment by Zheng222** [comment]
@xinntao Thanks for you reply!
