### ISSUE TITLE
Why didn't you used L1 and L2 regularizers to reduce BN artifacts?

### ISSUE THREAD

**Issue by bckpkol** [xinntao/ESRGAN#70]
Cause everyone else does.
Also, there's less of these artifacts with sigmoid activation.

**Comment by bckpkol** [comment]
Tried to train with your architecture. Regularization won't work, the artifacts are just like yours. Didn't tried sigmoid, though. But I understand why you don't want it.

**Comment by bckpkol** [comment]
Or, batch normalization could produce such a result if you have a too large kernel.

**Comment by xinntao** [comment]
I think the BN artifacts are from the BN layers (the mismatched estimated mean and variance). L1 and L2 regularization may not be effective to remove these artifacts. 
Simply removing BN layers in the network architecture can reduce the artifacts without affecting the final performance.
