### ISSUE TITLE
Your pre-trained model on lossy JPEG images

### ISSUE THREAD

**Issue by Neltherion** [xinntao/ESRGAN#9]
Thanks for sharing your code and approach.

But testing your approach using everyday images is a hard task since the images are mostly JPEGs and have noisy artifact blocks and in 99% of cases we don't have access to the RAW noiseless version of the images.

Can you provide a pre-trained model on noisy images? I'm curious to see if the SRGAN-based methods only do nicely on the noiseless raw images or if they can do both DeNoising + SuperResolution too?

Thanks again.

**Comment by xinntao** [comment]
Hi, @Neltherion 
Yes, the problem you mentioned is very common in the real-world scenarios.

A very simple way is to train (or fine-tune) the models to noisy images. But I may not have time to prepare the data and train these models in the next few months. 

You may have a try using the codes :smiley:
